### PR TITLE
Create harbour-vodman-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted.

### CODE REVIEW

**Comment by jgressmann** [comment]
Hi eson57,

thank you for your translation. 

Unfortunately I messed up some of the `<source>` fields so they don't have the full text. Please have a look at the English texts in [harbour-vodman.ts](harbour-vodman/src/vodman-app/translations/harbour-vodman.ts). You'll find the target strings in the `<translation>` fields.

Cheers
J

**Comment by eson57** [comment]
Hope this is right then. You wanted me to translate changes that was already in translation strings?

**Comment by jgressmann** [comment]
Well, yes if you would.

If you compare the `<translation>` tags in harbour-vodman.ts with your file you'll notice that some of the texts are quite a bit longer. 

I simply didn't know how to put multi line strings in the `<source>` tags via code annotations.

Cheers
J

**Comment by eson57** [comment]
OK then, looks good on my xperia x now.

**Comment by jgressmann** [comment]
Thank you for fixing the texts.

I have added the translation file and included you as translator on the
'about vodman' page. Please have a look.

Cheers,
J

**Comment by eson57** [comment]
Well, this is way out of my league, but git says there is conflicts. Are you sure this Pr is OK?

**Comment by jgressmann** [comment]
The reason there is a conflict is that I merged your translation along with the changes to the about page.

From the looks of it your patch doesn't include the missing texts, for instance `<message id="about-translations-header">` is missing.

To have a clean merge I would suggest that you update your clone of harbour-vodman to the latest master branch of my repo. Then add the missing texts and open a new pull request.

Cheers
J

**Pull request closed without merging**
