### PR TITLE
just add my name into translator,thanks

### PR DESCRIPTION
**Pull request by dashinfantry**

### CODE REVIEW

**Review by jgressmann — CHANGES_REQUESTED** [review]
Your name goes where it says dahinfantry.

**Comment by jgressmann** [comment]
Also, please translate anything with type="unfinished".
Thank you.

**Comment by dashinfantry** [comment]
https://github.com/jgressmann/harbour-vodman/compare/master...dashinfantry:patch-3 finished！

**Comment by jgressmann** [comment]
Hello, 
請將郵件標記翻譯為“unfinished”。 你不需要翻譯“未完成”這個詞：D

I hope this makes sense to you, Google translated it :/

**Pull request closed without merging**
